# Generated by Django 4.2.3 on 2023-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_blogappuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogappuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
