# Generated by Django 4.2.3 on 2023-08-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_blogappuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='accounts/default-avatar-profile-icon-of-social-media-user-vector.jpg', null=True, upload_to=''),
        ),
    ]
