version: '3.8'

services:
  web:
    image: sonyaharalambieva/blog_app_production
    build: .
    command: gunicorn --bind=0.0.0.0:8000 blog_app.wsgi:application
    platform: linux/amd64
    volumes:
      - ./staticfiles:/tmp/blog_app/staticfiles
      - ./mediafiles:/tmp/blog_app/mediafiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=greenhometips.info
    env_file:
      - ./envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: greenhometips
      POSTGRES_HOST: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web
    depends_on:
      - web
