version: '3.4'

services:
  web:
    image: blog_app
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: blogdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data