# Generated by Django 4.2.3 on 2023-08-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articles_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
