# Generated by Django 4.2.3 on 2023-08-13 04:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_articles_likes_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
