# Generated by Django 4.2.3 on 2023-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_articles_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='status',
        ),
        migrations.AddField(
            model_name='articles',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
